// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:timely/config/env.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// Provides platform-specific Firebase configuration options.
///
/// This class contains [FirebaseOptions] configurations for supported platforms
/// (Android and iOS) and provides a convenience getter to automatically select
/// the appropriate configuration based on the current platform.
///
/// Generated by FlutterFire CLI and customized to use [Env] credentials.
class DefaultFirebaseOptions {
  /// Returns the [FirebaseOptions] for the current platform.
  ///
  /// Automatically detects the platform and returns the corresponding
  /// configuration. Throws [UnsupportedError] for web, macOS, Windows, and Linux.
  ///
  /// Example:
  /// ```dart
  /// await Firebase.initializeApp(
  ///   options: DefaultFirebaseOptions.currentPlatform,
  /// );
  /// ```
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// Firebase configuration options for Android platform.
  ///
  /// Uses credentials from [Env] to configure Firebase for Android.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: Env.androidApiKey,
    appId: Env.androidAppId,
    messagingSenderId: Env.androidMessagingSenderId,
    projectId: Env.androidProjectId,
    storageBucket: Env.androidStorageBucket,
  );

  /// Firebase configuration options for iOS platform.
  ///
  /// Uses credentials from [Env] to configure Firebase for iOS.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: Env.iosApiKey,
    appId: Env.iosAppId,
    messagingSenderId: Env.iosMessagingSenderId,
    projectId: Env.iosProjectId,
    storageBucket: Env.iosStorageBucket,
    iosBundleId: Env.iosBundleId,
  );
}
